CREATE DATABASE QLKS4

go
use QLKS4

CREATE TABLE THEMPHONG (
    SO_PHONG			INT  NOT NULL PRIMARY KEY,
    LOAI_PHONG			NVARCHAR (50) NOT NULL,
    LOAI_GIUONG     	NVARCHAR (100) NOT NULL,
    GIA_TIEN			BIGINT        NOT NULL,
    TRANG_THAI			VARCHAR (50)  DEFAULT ('NO') NULL
);

CREATE TABLE DANGKY_KHACHHANG (
    ID_KHACHHANG		INT         PRIMARY KEY,
    TEN_KHACHHANG		NVARCHAR (100) NOT NULL,
    SO_DIEN_THOAI		BIGINT        NOT NULL,
    QUOC_TICH			VARCHAR (100) NOT NULL,
    GIOI_TINH			NVARCHAR (50)  NOT NULL,
    NGAY_SINH			DATETIME  NOT NULL,
    MA_DINH_DANH		VARCHAR (100) NOT NULL,
    DIA_CHI				NVARCHAR (350) NOT NULL,
    DANG_KY				DATETIME NOT NULL,
    SO_PHONG			VARCHAR (100) NOT NULL,
);

CREATE TABLE THANHTOAN (
	MA_THANH_TOAN		INT		PRIMARY KEY,
	THANH_TOAN			VARCHAR (50) DEFAULT ('NO') NULL,
	NGAY_THANH_TOAN		DATETIME    NULL,
	ID_KHACHHANG		INT			NOT NULL,
	FOREIGN KEY (ID_KHACHHANG) REFERENCES DANGKY_KHACHHANG (ID_KHACHHANG)
);

CREATE TABLE NHANVIEN (
    ID_NHANVIEN     		VARCHAR	 (50) NOT NULL,
    TEN_NHANVIEN    		NVARCHAR (100) NOT NULL,
    SO_DIEN_THOAI   		BIGINT        NOT NULL,
    GIOI_TINH				NVARCHAR (50)  NOT NULL,
    EMAIL					VARCHAR (100) NOT NULL,
    TEN_DANG_NHAP 			VARCHAR (150) NOT NULL,
    MAT_KHAU				VARCHAR (150) NOT NULL,
	QUYEN					VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED (ID_NHANVIEN ASC)
);

INSERT INTO NHANVIEN (ID_NHANVIEN, TEN_NHANVIEN, SO_DIEN_THOAI, GIOI_TINH, EMAIL, TEN_DANG_NHAP, MAT_KHAU, QUYEN)
VALUES 
  ('NV000', N'Admin', 0123123123, N'Nam', 'admin@gmail.com','admin','abc','Admin'),
  ('NV001', N'Nguyễn Thị An', 0123456789, N'Nữ', 'annguyen@gmail.com','annguyen','123','NhanVien'),
  ('NV002', N'Trần Văn Bình', 9876543210 ,'Nam', 'bintran@gmail.com' ,'binhtran','123','NhanVien'),
  ('NV003', N'Trần Nguyễn Anh Khoa', 987654321 ,'Nam', 'khoatran@gmail.com' ,'khoatran','123','NhanVien'),
  ('NV004', N'Đào Văn Việt', 123456789, 'Nam', 'vietdao@gmail.com' ,'vietdao','123','NhanVien'),
  ('NV005', N'Nguyễn Phước Toàn', 1230987621,'Nam', 'toannguyen@gmail.com' ,'toannguyen','123','NhanVien');
